{
    "name": "Product Warehouse Quantity Kanban",
    "summary": """Kanban view to see product warehouse quantity""",
    'sequence': -100,
    "version": "14.0.0.0.2",
    'category': 'Warehouse',
    "license": "LGPL-3",
    "author": "Zoldyck-Tech,Gunalan D",
    'maintainer': "Zoldyck-Tech",
    "depends": ['base','stock'],
    "data": [
        "views/views.xml",
    ],
    'demo': [],
    'qweb': [],
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
